services:
  - type: web
    name: cinco-quiz-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        value: https://cinco-quiz.vercel.app
      - key: PORT
        value: 5000
